//! Generate the redistributable OpenECS smoke corpus.
//!
//! The smoke corpus is a tiny, license-clean, *synthetic* set of EEG-shaped
//! EDF files that ships in-repo so OpenECS runs offline with zero external data.
//! It is NOT patient data (CHB-MIT / TUH are not redistributable); it is a
//! deterministic sum of band-placed sinusoids in the EDF i16 digital domain,
//! reproducible byte-for-byte by re-running this generator.
//!
//! Run from the crate root:
//!
//! ```bash
//! cargo run --example gen_smoke_corpus
//! ```
//!
//! It writes `corpora/smoke/*.edf` and prints the `[[file]]` blocks (with
//! real SHA-256 + shape) to paste into `corpora/ecs-smoke.toml`.

use std::f64::consts::PI;
use std::path::PathBuf;

use open_eeg_codec_standard::corpus::sha256_hex;
use open_eeg_codec_standard::subprocess::write_edf_bytes;

/// One synthetic EEG-shaped channel: a deterministic sum of band-placed
/// sinusoids (delta/theta/alpha/beta/gamma) + a small DC term, scaled to a
/// few hundred ADC counts, well inside the i16 digital range. No RNG, so the
/// output is byte-stable across runs and machines.
fn channel(ch: usize, n: usize, fs: f64) -> Vec<i64> {
    let amp = 1.0 + 0.2 * ch as f64;
    let phase = 0.37 * ch as f64;
    (0..n)
        .map(|i| {
            let t = i as f64 / fs;
            let v = amp
                * (30.0
                    + 110.0 * (2.0 * PI * 2.0 * t + phase).sin()
                    + 70.0 * (2.0 * PI * 6.0 * t).sin()
                    + 55.0 * (2.0 * PI * 10.0 * t + phase).sin()
                    + 28.0 * (2.0 * PI * 20.0 * t).sin()
                    + 12.0 * (2.0 * PI * 40.0 * t).sin());
            v.round() as i64
        })
        .collect()
}

fn signal(n_chan: usize, n: usize, fs: f64) -> Vec<Vec<i64>> {
    (0..n_chan).map(|c| channel(c, n, fs)).collect()
}

fn main() {
    // (file name, channels, samples/channel, fs) — small + diverse shapes.
    let specs: &[(&str, usize, usize, f64)] = &[
        ("synthetic_a.edf", 4, 1024, 256.0),
        ("synthetic_b.edf", 6, 768, 128.0),
        ("synthetic_c.edf", 2, 512, 256.0),
    ];

    let out_dir: PathBuf = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("corpora")
        .join("smoke");
    std::fs::create_dir_all(&out_dir).expect("create corpora/smoke");

    println!("# Generated by `cargo run --example gen_smoke_corpus`.");
    println!("# Paste the [[file]] blocks below into corpora/ecs-smoke.toml.\n");
    for (name, n_chan, n_samp, fs) in specs {
        let sig = signal(*n_chan, *n_samp, *fs);
        let edf = write_edf_bytes(&sig, *fs).expect("synthetic signal -> EDF");
        let path = out_dir.join(name);
        std::fs::write(&path, &edf).expect("write edf");
        let sha = sha256_hex(&edf);
        println!("[[file]]");
        println!("path = \"smoke/{name}\"");
        println!("sha256 = \"{sha}\"");
        println!("fs = {fs:.1}");
        println!("n_chan = {n_chan}");
        println!("n_samples = {n_samp}");
        println!();
        eprintln!("wrote {} ({} bytes, sha {})", path.display(), edf.len(), &sha[..12]);
    }
}
